/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pokornap' at '4/5/17 4:24 PM' with Gradle 3.1
 *
 * @author pokornap, @date 4/5/17 4:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
